In [8]:
import numpy as np
import wave
from scipy.io import wavfile
import torch
import torchaudio
import pyaudio
import wave
import time


for i in range(1, 50):    
    _, datas = wavfile.read(('./data/01/0_01_' + str(i) + '.wav'))
    data, samplerate = torchaudio.load(('./data/01/0_01_' + str(i) + '.wav'))
   
    length = datas.shape[0] / samplerate
    print(f"length = {length}s")
   
    print('samplerate:', samplerate)
    print(data, '\n')
   
    chunk = 1024  
    #open a wav format music  
    f = wave.open(('./data/01/0_01_' + str(i) + '.wav'),"rb")  
    #instantiate PyAudio  
    p = pyaudio.PyAudio()  
    #open stream  
    stream = p.open(format = p.get_format_from_width(f.getsampwidth()),  
                channels = f.getnchannels(),  
                rate = f.getframerate(),  
                output = True)  
    #read data  
    data = f.readframes(chunk)  
 
    #play stream  
    while data:  
        stream.write(data)  
        data = f.readframes(chunk)  
 
    #stop stream  
    stream.stop_stream()  
    stream.close()  
 
    #close PyAudio  
    p.terminate()  
    time.sleep(.5)

length = 0.65325s
samplerate: 48000
tensor([[6.1035e-05, 6.1035e-05, 6.1035e-05,  ..., 5.7983e-04, 5.7983e-04,
         5.4932e-04]]) 

length = 0.7729791666666667s
samplerate: 48000
tensor([[-0.0009, -0.0009, -0.0009,  ..., -0.0002, -0.0001, -0.0001]]) 

length = 0.8206041666666667s
samplerate: 48000
tensor([[ 9.1553e-05,  6.1035e-05,  9.1553e-05,  ..., -6.4087e-04,
         -6.7139e-04, -6.7139e-04]]) 



KeyboardInterrupt: 